sponsors = [
		("Beyamor", "http://www.wordsinthesky.com/"),
		("Olaf Godredsson", "http://www.newgrounds.com/portal/view/642802"),
		("Justin Smith", "http://www.captain-games.com/"),
]

sidebar_links = [
    (3, "DEVIANT ART", "http://coltonphillips.deviantart.com/gallery/"),
    (2, "FACEBOOK", "https://www.facebook.com/ColtonPhillipsArt"),
    (2, "TWITTER", "https://twitter.com/ColtonJPhillips"),
    (1, "BANDCAMP", "http://www.coltonphillips.bandcamp.com"),
    (1, "YOUTUBE", "http://www.youtube.com/user/ColtonPhillips"),
    (12, "PROGRESS","/progress"),
	(2, "VERB THE NOUN", "/verbthenoun"),
    (3, "SKETCHES", "/sketches"),
	(12, "COMIC","/comic"),
	(6, "GEAR", "/gear"),
	(12, "INDIE WISH LIST", "/indiewishlist"),
	(6, "COOL FOLK", "/coolfolk"), 
	(8, "TODO", "/todo"),
	(2, "LOGO", "/logo"),
	(6, "COMPLAIN", "/complain"),
    (1, "GITHUB", "https://github.com/ColtonPhillips"),
	(2, "ITCH.IO GAMES", "http://coltonphillips.itch.io"),
	(8, "STEAM", "http://steamcommunity.com/profiles/76561198019231307/"),
	(12, "VIMEO", "https://vimeo.com/coltonphillips"),
	(12, "FLICKR", "https://www.flickr.com/photos/113567215@N05/"),
	(1, "RESUME","http://www.coltonphillips.ca/static/resume.pdf"),
	(1, "CONTACT","mailto:coltonjphillips@gmail.com"),
]

progress = "32"

project_images = "/static/images/projects/"
projects = [
{
    "chance":1,
    "title": "Plug and Play Games: Harry Potter and the Magical Castle",
	"link": "/static/plugandplay.html",
    "description": "This dungeons and puzzling game was created for OrcaJam 2017 by Rose Dubord-Goulet, Adam Caflisch, Brandon Duncan, and myself",
		"thumbnail":  project_images + "plugandplay-thumb.gif",
		"header": project_images + "plugandplay-header.png",
}, {
{
    "chance":4,
    "title": "Everybody Coughs",
	"link": "/static/EverybodyCoughs.pdf",
    "description": "A picture poem for kids to think about mortality and stuff. Life is scary, so it's best to spook the kids when they are older.",
		"thumbnail":  project_images + "cough-thumb.gif",
		"header": project_images + "cough-header.png",
	}, {
    "chance":1,
    "title": "Super Mario Maker Courses!",
	"link": "/mario",
    "description": "I built an app to display Wii U IDs for the various courses I have created. This is done in python using html request scraping. Hey! Please Star my levels!",
		"thumbnail":  project_images + "mario-thumb.gif",
		"header": project_images + "mario-header.png",
	}, {
    "chance":1,
	"title": "Laughing Hand website",
	"link": "http://www.laughinghand.com",
		"description": "In 2014 I started working for artist Keith McKellar. I updated and refactored the Laughing Hand website to speed up page loading. I designed a book displaying his work in the Vancouver Neon street art. Some of the pages are over 17 years old.",
		"thumbnail":  project_images + "laughinghand-thumb.gif",
		"header": project_images + "laughinghand-header.png",
	}, {
        "chance":2,
		"title": "The Solid Bros",
		"link": "https://www.youtube.com/thesolidbrothers",
		"description": "A Youtube channel where best friends play video games together! We've made over 300 videos and some of them are pretty great!",
		"thumbnail":  project_images + "tsb-thumb.gif",
		"header": project_images + "tsb-header.png",
	}, {
        "chance":16,
		"title": "Concentric 2013",
		"link": "https://www.youtube.com/watch?v=MJw9W45Hhyw",
		"description": "An insanely drawn out comedic documentary at a gaming convention. This thing is so riduculous that I can't help but love it. Haha.",
		"thumbnail":  project_images + "concentric-thumb.gif",
		"header": project_images + "concentric-header.png",
	}, {

        "chance":8,
		"title": "Gremlin Alphabits",
		"link": "http://coltonphillips.bandcamp.com/album/gremlin-alphabits",
		"description": "An album of creative commons songs. This was an experiment to create music using Audacity as my sole D.A.W.S. and it was a lot of fun to do. Every song was done in a single take.",
		"thumbnail":  project_images + "gremlinalphabits-thumb.gif",
		"header": project_images + "gremlinalphabits-header.png",
	}, {

        "chance":8,
		"title": "The Brandon Duncan Experience",
		"link": "https://vimeo.com/89890427",
		"description": "The other elevator is a traitor. This is a very silly documentary style video taking place at GottaCon. I made it when I was finished demonstrating the Oculus Rift to the public with the Computer Science Faculty at UVic.",
		"thumbnail":  project_images + "bde-thumb.gif",
		"header": project_images + "bde-header.png",
	}, {

        "chance":4,
		"title": "Stigmata Jazz Hands",
		"link": "http://www.coltonphillips.ca/static/book/Stigmata Jazz Hands.pdf",
		"description": "A video game about reading a book. In some circles these sort of things are known as PDF files.",
		"thumbnail":  project_images + "stigmatajazzhands-thumb.gif",
		"header": project_images + "stigmatajazzhands-header.png",
	}, {
        "chance":2,
		"title": "Adipose Tissue",
		"link": "http://coltonphillips.itch.io/adiposeonline",
		"description": "A game about fat cells and avoiding damage inside of them. Created in Game Maker. It is playable on the Web, PC, or Android and uses box2d physics.",
		"thumbnail":  project_images + "adiposetissue-thumb.gif",
		"header": project_images + "adiposetissue-header.png",
	}, {
        "chance":8,
		"title": "Prophase 2",
		"link": "http://coltonphillips.itch.io/prophase-2", 
		"description": "An artistic game sort of thing that demonstrates some of my sketches, fears and ideas. It was sort of a reaction to the Internet's reaction to FEZ II being cancelled. Odd.",
		"thumbnail": project_images + "prophase2-thumb.gif",
		"header": project_images + "prophase2-header.png",
	}, {
        "chance":3,
		"title": "Maniac Mansion",
		"link": "http://coltonphillips.bandcamp.com/album/maniac-mansion",
		"description": "Maniac Mansion captures a piece of my life's work in the Maniac Mansion with Lee Gauthier as an auditory projection of the moments of play my friends and I have engaged in. The album is meant to satiate funders of the Colton Phillips' Humble Indie Fund. ",
		"thumbnail": project_images + "maniacmansion-thumb.gif",
		"header": project_images + "maniacmansion-header.png",
	}, {
        "chance":1,
		"title": "Verb the Noun Theme Generator",
		"link": "https://github.com/ColtonPhillips/vtn-theme",
		"description": "A game jam theme generator in over 10 languages. Random(Verb) the Random(Noun). It was a lot of fun to compare all the different languages abilities in doing one specific task.",
		"thumbnail": project_images + "vtngen-thumb.gif",
		"header": project_images + "vtngen-header.png",
	}, {
        "chance":7,
		"title": "wpdb.py",
		"link": "https://github.com/ColtonPhillips/wpdb",
		"description": "Open source python research project involving scientific inquiry into the Wikipedia API.",
		"thumbnail": project_images + "wpdb-thumb.gif",
		"header": project_images + "wpdb-header.png",
	}, {
        "chance":3,
		"title": "NEPTUNE: Ocean Explorer",
		"link": "http://wordsinthesky.com/projects/neptune-ocean-explorer",
		"description": "A horizontal prototype of an underwater ocean exploration game. Our ENGR 499 team worked directly with NEPTUNE Canada when making this game.",
		"thumbnail": project_images + "neptune-thumb.gif",
		"header": project_images + "neptune-header.png",
	}, {
        "chance":2,
		"title": "Gnar Play",
		"link": "http://www.youtube.com/watch?v=7XFv6swVUwo",
		"description": "A series of ten classic Let's Play videos with a cast of wacky characters.",
		"thumbnail": project_images + "gnarplay-thumb.gif",
		"header": project_images + "gnarplay-header.png",
	}, {
        "chance":1,
		"title": "Corvus",
		"link": "http://coltonphillips.itch.io/corvus-game",
		"description": "A web game collab by Marta Ligocki and I. I was responsible for the code (Flashpunk). This game was made at OrcaJam in Victoria BC. A soundscape experience for children.",
		"thumbnail": project_images + "corvus-thumb.gif",
		"header": project_images + "corvus-header.png",
	}, {
        "chance":6,
		"title": "Gnar Games",
		"link": "http://www.youtube.com/watch?v=AgpQuuC2KxA",
		"description": "Seven Episode series of GameDev updates toward the Dinosaurs In Spacei python (pygame) prototype.",
		"thumbnail": project_images + "gnargames-thumb.gif",
		"header": project_images + "gnargames-header.png",
	}, {
        "chance":1,
		"title": "Splurgle",
		"link": "https://www.youtube.com/watch?v=wfL3VTGdY5M",
		"description": "My work on Roly Poly 2 helped towards shipping Splurgle. I developed on it for about 2 weeks including multiple functional game objects. For LeapPad 2.",
		"thumbnail": project_images + "splurgle-thumb.gif",
		"header": project_images + "splurgle-header.png",
	}, {
        "chance":1,
		"title": "Roly Poly 2: Treasure Hunt",
		"link": "https://www.youtube.com/watch?v=0j2PN4sWgHw",
		"description": "I helped program a children's game for the LeapPad at InLight Entertainment during my 4th Coop as a Software Engineer in training. For LeadPad 2.",
		"thumbnail": project_images + "roly2-thumb.gif",
		"header": project_images + "roly2-header.png",
	}, {
        "chance":3,
		"title": "Colton and Tom's Good Time Text Adventure",
		"link": "http://www.wordsinthesky.com/projects/colton-and-toms-good-time-text-adventure",
		"description": "A chincy little text adventure with a surprise twist. A collab with the Tomster. For Windows.",
		"thumbnail": project_images + "catgtta-thumb.gif",
		"header": project_images + "catgtta-header.png",
	}, {
        "chance":2,
		"title": "You Can't Go Through The Door",
		"link": "http://coltonphillips.itch.io/you-cant-go-through-the-door",
		"description": "Ludum Dare 22. Theme: Alone. Controls: Home Row Keys. For Windows.",
		"thumbnail": project_images + "ycgttd-thumb.gif",
		"header": project_images + "ycgttd-header.png",
	}, {
        "chance":1,
		"title": "UVic GameDev",
		"link": "http://www.facebook.com/groups/UVicGameDev",
		"description": "I cofounded the University of Victoria's Student Society Game Development Club and presided over it for a while.",
		"thumbnail": project_images + "uvgd-thumb.gif",
		"header": project_images + "uvgd-header.png",
	}, {
        "chance":2,
		"title": "Beware The Lunar Light",
		"link": "http://www.youtube.com/watch?v=dSTC_A8yX5k",
		"description": "A short film I helped produce with Rayln Gladue in grade six about about a boy who turns into a werewolf. Twenty five minutes long.",
		"thumbnail": project_images + "btll-thumb.gif",
		"header": project_images + "btll-header.png",
	}, {
        "chance":1,
		"title": "Gremlin Kickball",
		"link": "http://coltonphillips.itch.io/gremlin-kickball",
		"description": "My very first game. I made this for a high school math class to demonstrate the use of applied mathematics. Two players. For Windows.",
		"thumbnail": project_images + "gremlinkickball-thumb.gif",
		"header": project_images + "gremlinkickball-header.png",
	},{
        "chance":8,
        "title": "SPONSOR: Justin Smith",
        "link": "http://captaingames.itch.io/",
        "description": "Justin Smith has been making the World's Greatest Video Games since before you were born.",
        "thumbnail":  project_images + "justinsmith-thumb.gif",
       "header": project_images + "justinsmith-header.png",
    }, {
      "chance":8,
       "title": "SPONSOR: ChillaBounce HD",
       "link": "http://www.kongregate.com/games/OlafGodredsson/chillabouncehd",
       "description": "A fun and challenging game from Godredsson Games.",
       "thumbnail":  project_images + "chillabounce-thumb.gif",
       "header": project_images + "chillabounce-header.png",
    }
]

gear = ["Canon EOS Rebel T3I",
	"Standard Tripod",
	"Korg MIDI Keyboard",
	"Reason Essentials",
	"Hexels Pro", 
	"Takamine Acoustic Guitar",
	"Love Rock Electric Guitar",
	"Alesis Vortex Keytar",
	"Akai LPK25 Keyboard",
	"Zoom H4 Handy Recorder",
	"Game Maker Studio Game Engine (PC, Android, HTML5)",
	"WM Capture Screen Record and Media File Converter",
	"PICO-8 Game Engine",
	"Adobe Creative Cloud (e.g. Photoshop)",
	]

wishes = ["GBA, DS, 3DS game cartridges", 
	"One XBOX USB controller", 
	"Japanese literature for beginners", 
	"Over the ear studio quality monitor headphones", 
	"Apple desktop or notebook",
	"Tripod for Canon EOS Rebel",
	"A Badass office chair to park my big fat ass",
	]

stuff = ["Original XBOX with 4 controllers", 
	"Dell Windows 7 Netbook", 
	"Awesome large wolf painting", 
	"Goldeneye for Wii and also N64", 
	"Slim Playstation 2 with missing power cord", 
	"George Foreman Grill", 
	"Legend of Zelda: Ocarina of Time (N64)", 
	"Beerfest, W (G. Bush)", 
	"Board Games (Seinfeld Scene It, Lord of the Rings Risk, Balderdash)", 
	"Deep frier appliance", 
	"Windows Kinect Sensor",
	]

all_definitions = {
                "SIDEBAR_LINKS": sidebar_links,
		"SPONSORS": sponsors,
                "PROJECTS": projects,
                "GEAR": gear,
		"WISHES": wishes,
		"STUFF": stuff,
        "PROGRESS": progress
}
