statuses = [
"This feature took me way too long to implement",
"Hamburgers",
"So rando lol Much statuses",
"My good pal Tom helped make this cool site",
"This website uses the Javiest of Javascripts",
"Brandon Duncan made me this way",
"I'm not joking.",
"This is not a test",
"Just kidding!",
"Here I am, Senior Internet User. Take me.",
"Welcome to the frump page of the Internet",
"I only do everything",
"What? Me worry?",
"One Million! How many can I give you!",
"Hello World!",
"I watch Netflix until my eyes bleed red white and black.",
"I am the watcherman. I watch the watchmen's watches to check the time.",
"I invent jokes so you don't have to.",
"Remember that episode of The Simpsons? I do.",
"I want to do all of the things I haven't done yet.",
"I work hard to solve hard problems.",
"JQuery? Yes. Hellck yis.",
"I'm a comedy man with a comedy plan.",
"This website is powered by dark magic and dragon tears.",
"I once cried because I was amazing at life.",
"I cried during one of the LOTR movies. Guess which one for 50 points.",
"Points? Oh yeah. Points, baby. Mo' fuckin' points up in hurr.",
"I invented the Internet.",
"Check out my wares. Y'all on Github roight?",
"I'm cold and calculated. I've read every bonding and attachment book there is.",
"This is a website that was built on lies and hypocracy. Welcome!",
"Welcome to the jungle. We got grumpin games.",
"Sha na na na na na na na neeeee neee neeeeee!",
"Phone your mom.",
"Can I get your ethical opinion on my radness?",
"Five bucks?",
"Hey! I EARNED that five books!",
"I take the language you langed when you wages.",
"I shooked a speak at a spears baked bread.",
"Skark Tank VS Dragon's Nest.",
"Verb the Noun",
"Noun the Verb",
"Noun the Noun",
"Verb the Verb",
"I believe you took my stapler.",
"Kill the president!",
"Seed: 'Jontronraptor'",
"from random import choose",
"Python is the best language, but man... Perl...",
"If you got time to clean, you got time to lean.",
"I'm a mean meaning machine.",
"Grr!",
"HI I'M COLTON PHILLIPS AND I LIKE THINGS REAL GOOD",
]
