statuses = [
"This feature took me way too long to implement",
"Hamburgers",
"I consider myself lucky to have such nice friends",
"Maximum potato achieved.",
"Author of such books as books and books",
"My cell phone is a cell phone and so can you!",
"vim. Use it!",
"I'm using vim more than you breath.",
"Can I get a heck yes?",
"Knock knock!",
"y'all got your python shoes on right?",
"Static Twitter awesomeness",
"Big fat kitty cat",
"Leftover french fries",
"I love programming stuff AND things :3",
":3 Meow!",
"This website is SO fetch! ~~~",
"I'm an expert minecraft user. Ask me anything!",
"Take all your problems and rip em apart.",
"Shop till you drop!",
"I'm still kickin'",
"I was an adorable child.",
"I love sodey pop.",
"I like it when you smile.",
"Positive!",
"Let's all do our best, kiki!",
"I write code at a 50000th grade level.",
"I'm a poet and I didn't even know it.",
"I use sneaky tricks to make jokes.",
"I'm a jokefiend. Jokesmith, even.",
"Press escape.",
"Have you tried pressing Alt+F4",
"I'm a master at Windows but I'll use Linux any time you want to see if I'm in fact a cool guy.",
"Cool guy riding in a cool car.",
"One time I saw Tom in these cool glasses and I was all 'Man he's cool.'",
"Minecraft on your nintendo box! IDEAS IDEAs IDEAS",
"I paint pictures of pictures. e.",
"I'm learning Japanese. Watashi sugoi esse, holmes?",
"I put pictures of cats on my wall. See what I'm saying, boss?",
"I don't ever want to not pet a cat.",
"I'm a good guy. Ask anyone. Oh god not him!",
"I've done zero deals with the devil. I've done thousands of deals for devil'd eggs though...",
"So rando lol Much statuses",
"My good pal Tom helped make this cool site",
"This website uses the Javiest of Javascripts",
"Brandon Duncan made me this way",
"I'm not joking.",
"This is not a test",
"Just kidding!",
"Here I am, Senior Internet User. Take me.",
"Welcome to the frump page of the Internet",
"I only do everything",
"What? Me worry?",
"One Million! How many can I give you!",
"Hello World!",
"I watch Netflix until my eyes bleed red white and black.",
"I am the watcherman. I watch the watchmen's watches to check the time.",
"I invent jokes so you don't have to.",
"Remember that episode of The Simpsons? I do.",
"I want to do all of the things I haven't done yet.",
"I work hard to solve hard problems.",
"JQuery? Yes. Hellck yis.",
"I'm a comedy man with a comedy plan.",
"This website is powered by dark magic and dragon tears.",
"I once cried because I was amazing at life.",
"I cried during one of the LOTR movies. Guess which one for 50 points.",
"Points? Oh yeah. Points, baby. Mo' fuckin' points up in hurr.",
"I invented the Internet.",
"Check out my wares. Y'all on Github roight?",
"I'm cold and calculated. I've read every bonding and attachment book there is.",
"This is a website that was built on lies and hypocracy. Welcome!",
"Welcome to the jungle. We got grumpin games.",
"Sha na na na na na na na neeeee neee neeeeee!",
"Phone your mom.",
"Can I get your ethical opinion on my radness?",
"Five bucks?",
"Hey! I EARNED that five books!",
"I take the language you langed when you wages.",
"I shooked a speak at a spears baked bread.",
"Skark Tank VS Dragon's Nest.",
"Verb the Noun",
"Noun the Verb",
"Noun the Noun",
"Verb the Verb",
"I believe you took my stapler.",
"Kill the president!",
"Seed: 'Jontronraptor'",
"from random import choose",
"Python is the best language, but man... Perl...",
"If you got time to clean, you got time to lean.",
"I'm a mean meaning machine.",
"Grr!",
"HI I'M COLTON PHILLIPS AND I LIKE THINGS REAL GOOD",
]
