statuses = [
"random(random())",
"Let me gif you the gist of it",
"Bananas are good",
"Cereal is kind of sugary",
"Looks like corn flakes in the news again...",
"You can't even dodge that!",
"How much health do you have?!",
"Pretzels and cheese, whatever.",
"You go, girt!!",
"Jump over this or go underneath it.",
"I ate too much food before lunch! You gotta dodge food!",
"Take your glucose",
"Oh! I'm learning!",
"I'm workin' my glucose.",
"See you again next time on Gnar Play thanks for comin' out.",
"Look at them Mode 7 Graffx!",
"Mode 7!!",
"This feature took me way too long to implement",
"Hamburgers",
"I consider myself lucky to have such nice friends",
"vim. Use it!",
"I'm using vim more than you breath.",
"Can I get a heck yes?",
"Knock knock!",
"Y'all got your python shoes on right?",
"Big fat kitty cat",
"Leftover french fries",
"I love programming stuff AND things :3",
":3 Meow!",
"This website is SO fetch! ~~~",
"I'm an expert minecraft user. Ask me anything!",
"Take all your problems and rip em apart.",
"Shop till you drop!",
"I'm still kickin'",
"I was an adorable child.",
"I love sodey pop.",
"Positive!",
"Let's all do our best, kiki!",
"I'm a poet and I didn't even know it.",
"Have you tried pressing Alt+F4",
"I'm a master at Windows but I'll use Linux any time you want to see if I'm in fact a cool guy.",
"Cool guy riding in a cool car, baby c'mon.",
"One time I saw Tom in these cool glasses and I was all 'Man he's cool.'",
"I'm learning Japanese. Watashi sugoi esse, holmes?",
"I don't ever want to not pet a cat.",
"I'm a good guy. Ask anyone. Oh god not him!",
"I've done zero deals with the devil. I've done thousands of deals for devil'd eggs though...",
"So rando lol Much statuses",
"My good pal Tom helped make this cool site",
"This website uses the Javiest of Javascripts",
"Brandon Duncan made me this way",
"I'm not joking.",
"This is not a test",
"Just kidding!",
"Here I am, Senior Internet User. Take me.",
"Welcome to the frump page of the Internet",
"I only do everything",
"What? Me worry?",
"Hello World!",
"I am the watcherman. I watch the watchmen's watches to check the time.",
"I'm the Nostalgia Critic's Nostalgic Critic. I invent jokes so you don't have to.",
"Remember that episode of The Simpsons? I do.",
"I want to do all of the things I haven't done yet.",
"I work hard to solve hard problems.",
"JQuery? Yes. Hellck yis.",
"I'm a comedy man with a comedy plan.",
"This website is powered by dark magic and dragon tears.",
"I cried during one of the LOTR movies. Guess which one for 50 points.",
"Welcome to the jungle. We got grumpin games.",
"Sha na na na na na na na neeeee neee neeeeee!",
"Phone your mom.",
"Can I get your ethical opinion on my radness?",
"I shooked a speak at a spears baked bread.",
"Skark Tank VS Dragon's Nest.",
"Verb the Noun",
"Noun the Verb",
"Noun the Noun",
"Verb the Verb",
"I believe you took my stapler.",
"from random import choose",
"Python is the best language, but man... Perl...",
"If you got time to clean, you got time to lean.",
"I'm a mean meaning machine.",
"HI I'M COLTON PHILLIPS AND I LIKE THINGS REAL GOOD",
]
